### ISSUE TITLE
Main README link to envoy is broken

### ISSUE THREAD

**Issue by joe-getcouragenow** [googleapis/gnostic-grpc#27]
implement that API using [gRPC-JSON Transcoding](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/grpc_json_transcoder_filter

**Comment by LorenzHW** [comment]
Thanks for noticing. I think the new one would be:
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter
